<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Views\Coordinator\**" />
    <Compile Remove="Views\Manager\**" />
    <Compile Remove="Views\NewFolder\**" />
    <Content Remove="Views\Coordinator\**" />
    <Content Remove="Views\Manager\**" />
    <Content Remove="Views\NewFolder\**" />
    <EmbeddedResource Remove="Views\Coordinator\**" />
    <EmbeddedResource Remove="Views\Manager\**" />
    <EmbeddedResource Remove="Views\NewFolder\**" />
    <None Remove="Views\Coordinator\**" />
    <None Remove="Views\Manager\**" />
    <None Remove="Views\NewFolder\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="Views\Claims\PreApprove.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
